### ISSUE TITLE
How to add title and description 

### ISSUE THREAD

**Issue by samsantosh** [addpipe/Pipe-Android-SDK#3]
How to add a title and description for a video like gravity form from android

**Comment by octavn** [comment]
GF allows you to add title and description fields to any form that includes the Pipe recorder.

You should check out:

- the official [Gravity Forms Pipe Add-On](http://www.gravityforms.com/add-ons/pipe/)
- our earlier [tutorial for using the Pipe recorder in a GF form](https://addpipe.com/blog/record-video-with-gravity-forms-and-pipe-video-recorder/)

If you need more help you can contact us directly at hello@addpipe.com .

Closing this issue because it's not an issue.

**Comment by samsantosh** [comment]
I am asking about in Android integration not in gravity form... Ho can I
add title and description of a video from Android SDK this is my actual
question

**Comment by octavn** [comment]
>not in gravity form

You've literally mentioned "gravity form" in your 1st post.

>Ho can I add title and description of a video from Android SDK

Pipe only handles the video recording & processing, it does not store your personal data about the actual video.  

You can use the `payload` to pass custom data like user id or question id all the way to the webhooks and use those ids to link the information that comes through the webhook (video file name, length, URL, etc.) to a certain entry in your db.

**Comment by samsantosh** [comment]
I have mentioned that how can I add title and description like gravity form

On Oct 9, 2017 4:28 PM, "Octavian Naicu" <notifications@github.com> wrote:

not in gravity form

You've literally mentioned "gravity form" in your 1st post.

Ho can I add title and description of a video from Android SDK

Pipe only handles the video recording & processing, it does not store your
personal data about the actual video.

You can use the payload to pass custom data like user id or question id all
the way to the webhooks and use those ids to link the information that
comes through the webhook (video file name, length, URL, etc.) to a certain
entry in your db.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/addpipe/Pipe-Android-SDK/issues/3#issuecomment-335125271>,
or mute the thread
